services:
  autofill_characters:
    build:
      dockerfile: Dockerfile.goapps
      context: .
      target: final
      args:
        APPNAME: autofill_characters
      tags:
        - ghcr.io/slazurin/maple-culvert-tracker/autofill_characters
    env_file: .env
